### ISSUE TITLE
Auto-reloading side-view of the Basic UI

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-vscode#10]
### Background:
Currently when you have the Basic UI side-view open and work on your `*.sitemap` \ `*.items` file, there's no way to preview the changes you've applied.
A workaround is to close and reopen the Basic UI browser.

### Implementation:
Attach an action to `onDidSaveTextDocument` and refresh Basic UI view if it's open.

### Details:
https://code.visualstudio.com/docs/extensionAPI/vscode-api

https://github.com/Microsoft/vscode-extension-samples/blob/master/previewhtml-sample/src/extension.ts

https://github.com/openhab/openhab-vscode/blob/master/src/ContentProvider/openHAB.ts#L56

**Comment by dennisausbremen** [comment]
I played around with it a little and its a bag of hurt, since the "webview" is undebuggable, un-younameit. It's a pain and simply does not work correctly. 😠  You HAVE to use iframes since everything javascript is not correctly enabled because of "security", which you can read in the docs/gh issues. 

A workaround seems to have a useless counter variable that counts up everytime the 'onDidSaveTextDocument' fires. Which, if it works at all, either refreshes the view without any changes or sets the url, albeit being correctly logged, to something bogus and you are presented with the "Seems like you have not set a sitemap" page of openHab. 😢 

If you do not incorporate such trickery the webview will not change at all. 😞 

Maybe it's just too late and I'm not getting it either, who knows. 😄 🍻

**Comment by Confectrician** [comment]
We have to think of the webview anyways in a new direction.
The temporary replacement i have implemented has some issues too.

Closing for now.
