### ISSUE TITLE
.gitignore is missing useful defaults and contains existing files

### ISSUE THREAD

**Issue by thewilli** [openhab/openhab-vscode#134]
* the [.vscode directory](https://github.com/openhab/openhab-vscode/tree/91e7770c25c58ac3b73acf8103a8df5beba57a52/.vscode) is included in the repository while being [excluded by .gitignore](https://github.com/openhab/openhab-vscode/blob/91e7770/.gitignore#L8) at the same time.
* the .gitignore file should contain some useful defaults like [this one from gitignore.io](https://www.gitignore.io/api/node,linux,macos,windows,visualstudiocode).

I'll prepare a PR if you agree and tell me how you want to handle the `.vscode` directory

**Comment by Confectrician** [comment]
I think .vscode should be included since we can share tasks, settings, launch,... this way too.

@SamuelBrucksch excluded it with his last PR.
Don't know if it was on a special purpose.

For reference:
https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

Same goes for https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

I think there is a problem currently, when i checkout a PR or the master branch.
I think it was not comitted with the last changes.

**Comment by Confectrician** [comment]
Also i don't know if we need such an overflow of gitignore here.
I like to keep stuff simple and add things, if and when needed.

**Comment by thewilli** [comment]
> I think .vscode should be included since we can share tasks, settings, launch,... this way too.

sounds reasonable 👍 

> Also i don't know if we need such an overflow of gitignore here.

well, it doesn't reduce performance and IMHO prevents files from being accidentially added to the repository in the future. just doesn't *hurt*.

> I like to keep stuff simple

that's why I'd propose to base it on a maintained and tested template. Consider it auto-generated content like `package-lock.json`.

> and add things, if and when needed

no offense, but I made the experience that this often just doesn't work. many things delayed upon *once needed* were never done :wink:

**Comment by Confectrician** [comment]
We are doing reviews here, before merging a pull request, so i only see a small chance of merging unwanted stuff by accident.

I can remember forgetting .gitignore stuff only for repos where i worked on alone.
But my opinion is nothing more than an opinion like any other one. 🙂 

>"it doesn't hurt"

fair point. gitignore is really nothing to argue about.
