### ISSUE TITLE
Reload settings dynamically without restarting VS Code

### ISSUE THREAD

**Issue by LinqLover** [openhab/openhab-vscode#221]
## Is your feature request related to a problem? Please describe.
Currently, I need to reload my VS Code window after every OH-relevant change I have applied to the settings. This is not even documented anywhere, and if you get in trouble with the settings, it can impede debugging indeed.

## Describe the solution you'd like
The settings should be reloaded as often as possible, but at least when clicking any of the Refresh buttons in the openHAB panel of VS Code.

## Describe alternatives you've considered
Current workaround: _Developer > Reload Window_

## Additional context
This thread: [Visual Code and Openhab 3.0 - Off-Topic - openHAB Community](https://community.openhab.org/t/visual-code-and-openhab-3-0/109687/25)

**Comment by Confectrician** [comment]
Had a short lookup (and confusion why i didn't lok for this myself yet....).

This should be pretty straight forward with the `vscode.workspace.onDidChangeConfiguration()` event.

**Comment by Confectrician** [comment]
I have checked up on this and the problem is a bit different unfortunately.
The Hover action for example already works properly without the need to reload, since it gets the configuration on the fly when being used.
The extension utilities itself (or at least some of them) are caching the config on startup and make the reload necessary. 🤦‍♂️

So i have to improve that for every extension part on its own.
