### ISSUE TITLE
Add human readable cron desciptions to the hover provider

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-vscode#237]
**Describe the solution you'd like**

It would be pretty nice to recognise hovering over a cron expression in a `.rule` or `.persist` file and describe the expression in a human readable way.

**Additional context**
Possible ready to use library: https://github.com/bradymholt/cRonstrue
It is i18n ready, so also prepared for a i18n'ified extension.

**Comment by CWempe** [comment]
Actually, I would not make this part of the openHAB addon.

[Cron Explained](https://marketplace.visualstudio.com/items?itemName=tumido.cron-explained) does this already.
The advantage of that addon is it works for everything. Not only openHAB files.
And I do not know what happens if you have two addons for the same feature activated.

**Comment by Confectrician** [comment]
We then could recommend using cron explained in our extension instead.

Extensions can provide a `extensions.json` file and users then get recommendations to also use the configured extensions over there.

See: https://github.com/openhab/openhab-vscode/blob/main/.vscode/extensions.json

**Comment by CWempe** [comment]
Sounds like a good idea.

**Comment by Confectrician** [comment]
OK. Then we can add  `tumido.cron-explained` over there.
