### ISSUE TITLE
Add human readable Thread desciptions to the hover provider

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-vscode#240]
Just like the feature request for cron (#237) it would be great if there was a human readable description for the `Thread.sleep()` method in rules.

So lazy people like me do not have to calculate `Thread::sleep(420000)` to `7 minutes` ourselves. 😄

**Comment by Confectrician** [comment]
I know i am overloading myself with work (🙃):

But what about a little calculator for this, that inserts it as a snippet?
Probably there is already some kind of lib or api that could do the work.
We could then add a small area to the sidebar for this ( and possible other comfort functions in future).

**Comment by Confectrician** [comment]
Hey @CWempe 

What do you think about this presentation?
(Hopefully no one uses hour long thread sleeps... Mabye i shoulld remove that one.)

![image](https://user-images.githubusercontent.com/7161177/111215098-07c6e100-85d3-11eb-8497-1476f1b10340.png)

**Comment by CWempe** [comment]
I would prefer a simpler design in one line, I guess.

And I would get rid of leading zeros and `0` values at all to make it quicker and easier to read..

I am not sure what the best format would be either. 😕

Some ideas:

* `3h 43m 17s 10ms `, `5m 0s 10ms`
* `3:43:17.10`  (is this correct for ms?)
* `3 hours 43 minutes 17 seconds 10 milliseconds` (too long?!)
* ``


Looks like the [ISO 8601](http://www.doku.net/techndoku/artikel/iso8601dat.htm#:~:text=PnYnMnDTnHnMnS) is not the way to go: `P3Y6M4DT12H30M17S` 😆

**Comment by Confectrician** [comment]
I have changed to the one line version already, because of simplicity.
I have also added a formatting that avoids displaying zero values.
This way we are perfectly fine with using long words for the display.

![image](https://user-images.githubusercontent.com/7161177/111222682-72c8e580-85dc-11eb-987c-f8473fff9ece.png)

![image](https://user-images.githubusercontent.com/7161177/111222707-7a888a00-85dc-11eb-9233-a8558b73cd27.png)

![image](https://user-images.githubusercontent.com/7161177/111222720-7e1c1100-85dc-11eb-9308-47ff77acc820.png)

When i am really bored some time i will also try to adapt hours to hour, when the number is exactly one.

**Comment by CWempe** [comment]
Great!

btw: You might want to list this feature in the `README.md`. :)

**Comment by Confectrician** [comment]
Still looking for voluunteers to add a nice documentation we could then fetch into the docs.

BUt thats a long term topic...

**Comment by CWempe** [comment]
btw: I still think we do not need a description in the hover pop up.

![image](https://user-images.githubusercontent.com/1270359/111679954-ff181a00-8821-11eb-99b8-d95862bc5e74.png)

We do not have one for the Item state hover... 😉 

![image](https://user-images.githubusercontent.com/1270359/111680106-28d14100-8822-11eb-8302-ee72fe2dab71.png)

**Comment by Confectrician** [comment]
Yep. I left that out because of the poor formatting options we have over there.

Can you open a small new issue to track that?
I will bring it up before next release.
