### ISSUE TITLE
can't access REST API if authentication is enabled on openHAB

### ISSUE THREAD

**Issue by sumnerboy12** [openhab/openhab-vscode#25]
I have security enabled for both INTERNAL/EXTERNAL connections (openHAB v1.8.3) so vscode is unable to access the REST API to retrieve the item list. 

would it be possible to add optional username/password to settings to allow authentication?

**Comment by kubawolanin** [comment]
Hey @sumnerboy12 could you try a quick and dirty workaround for me?
In your user/workspace settings instead of providing your hostname / ip address in `openhab.host` field, try to iclude your credentials as well, e.g.:
```
{
	"openhab.host": "username:password@openhabianpi",
	"openhab.port": "8080"
}
```

And please let me know if it works!
This is just a temporary workaround - the real solution would be to provide two [new configuration properties[(https://github.com/openhab/openhab-vscode/blob/master/package.json#L119) and utilize it [here in the getHost](https://github.com/openhab/openhab-vscode/blob/master/src/Utils.ts#L32) method.
PR is welcome :-)

**Comment by sumnerboy12** [comment]
That seems to have worked - I am now getting a different error;

```
Error while connecting: nodes.sort is not a function
```

So I am guessing that authentication has worked!

**Comment by sumnerboy12** [comment]
Implemented the changes you suggested but haven't been able to test sorry.

**Comment by kubawolanin** [comment]
> That seems to have worked - I am now getting a different error;

Hmm can you tell me a bit more about what exactly are you protecting with basic auth?
Is it your OH host in general (covering REST API as well?) or specific pages (e.g. paperui, basic ui etc).
I need that information because right now we're using one `getHost` method for all endpoints.

**Comment by sumnerboy12** [comment]
OH host in general. Just standard OH authentication (remembering this is OH v1.8.3).
